--- a/drivers/staging/wilc1000/Makefile	2019-09-27 12:29:36.445475348 -0700
+++ b/drivers/staging/wilc1000/Makefile	2019-09-27 12:29:50.233507025 -0700
@@ -5,10 +5,10 @@
 			wilc_hif.o wilc_wlan_cfg.o wilc_debugfs.o \
 			wilc_wlan.o sysfs.o wilc_bt.o
 
-obj-$(CONFIG_WILC_SDIO) += wilc-sdio.o
+obj-$(CONFIG_WILC1000_SDIO) += wilc-sdio.o
 wilc-sdio-objs += $(wilc-objs)
 wilc-sdio-objs += wilc_sdio.o
 
-obj-$(CONFIG_WILC_SPI) += wilc-spi.o
+obj-$(CONFIG_WILC1000_SPI) += wilc-spi.o
 wilc-spi-objs += $(wilc-objs)
 wilc-spi-objs += wilc_spi.o 
